const airChange = 1.92;
exports.naturalVegitationMerges = [
  { start: { row: 3, column: 6 }, end: { row: 3, column: 7 } },
  { start: { row: 4, column: 6 }, end: { row: 4, column: 7 } },
  { start: { row: 5, column: 6 }, end: { row: 5, column: 7 } },
  { start: { row: 6, column: 6 }, end: { row: 6, column: 7 } },
  { start: { row: 7, column: 6 }, end: { row: 7, column: 7 } },
  { start: { row: 8, column: 6 }, end: { row: 8, column: 7 } },
  { start: { row: 9, column: 6 }, end: { row: 9, column: 7 } },
  { start: { row: 10, column: 6 }, end: { row: 10, column: 7 } },
  { start: { row: 11, column: 6 }, end: { row: 11, column: 7 } },
  { start: { row: 12, column: 6 }, end: { row: 12, column: 7 } },
  { start: { row: 3, column: 8 }, end: { row: 3, column: 9 } },
  { start: { row: 4, column: 8 }, end: { row: 4, column: 9 } },
  { start: { row: 5, column: 8 }, end: { row: 5, column: 9 } },
  { start: { row: 6, column: 8 }, end: { row: 6, column: 9 } },
  { start: { row: 7, column: 8 }, end: { row: 7, column: 9 } },
  { start: { row: 8, column: 8 }, end: { row: 8, column: 9 } },
  { start: { row: 9, column: 8 }, end: { row: 9, column: 9 } },
  { start: { row: 10, column: 8 }, end: { row: 10, column: 9 } },
  { start: { row: 11, column: 8 }, end: { row: 11, column: 9 } },
  { start: { row: 12, column: 8 }, end: { row: 12, column: 9 } },
  { start: { row: 14, column: 2 }, end: { row: 14, column: 3 } },
  { start: { row: 14, column: 4 }, end: { row: 14, column: 10 } },
  { start: { row: 17, column: 3 }, end: { row: 17, column: 6 } },
  { start: { row: 18, column: 3 }, end: { row: 18, column: 6 } },
  { start: { row: 19, column: 3 }, end: { row: 19, column: 6 } },
  { start: { row: 22, column: 2 }, end: { row: 22, column: 10 } },
  { start: { row: 23, column: 2 }, end: { row: 23, column: 4 } },
  { start: { row: 24, column: 2 }, end: { row: 24, column: 4 } },
  { start: { row: 25, column: 2 }, end: { row: 25, column: 4 } },
  { start: { row: 26, column: 2 }, end: { row: 26, column: 4 } },
  { start: { row: 27, column: 2 }, end: { row: 27, column: 4 } },
  { start: { row: 28, column: 2 }, end: { row: 28, column: 4 } },
  { start: { row: 29, column: 2 }, end: { row: 29, column: 4 } },
  { start: { row: 30, column: 2 }, end: { row: 30, column: 4 } },
  { start: { row: 31, column: 2 }, end: { row: 31, column: 4 } },
  { start: { row: 32, column: 3 }, end: { row: 32, column: 4 } },
  { start: { row: 32, column: 5 }, end: { row: 32, column: 6 } },
  { start: { row: 32, column: 7 }, end: { row: 32, column: 8 } },
  { start: { row: 32, column: 2 }, end: { row: 32, column: 4 } },
  { start: { row: 33, column: 2 }, end: { row: 33, column: 4 } },
  { start: { row: 34, column: 2 }, end: { row: 34, column: 4 } },
  { start: { row: 35, column: 2 }, end: { row: 35, column: 4 } },
  { start: { row: 36, column: 2 }, end: { row: 36, column: 4 } },
  { start: { row: 37, column: 3 }, end: { row: 37, column: 4 } },
  { start: { row: 38, column: 3 }, end: { row: 38, column: 4 } },
  { start: { row: 39, column: 2 }, end: { row: 39, column: 4 } },
  { start: { row: 40, column: 3 }, end: { row: 40, column: 4 } },
  { start: { row: 41, column: 3 }, end: { row: 41, column: 4 } },
  { start: { row: 42, column: 2 }, end: { row: 42, column: 4 } },
  { start: { row: 43, column: 3 }, end: { row: 43, column: 4 } },
  { start: { row: 44, column: 3 }, end: { row: 44, column: 4 } },
  { start: { row: 45, column: 2 }, end: { row: 45, column: 4 } },

  { start: { row: 47, column: 2 }, end: { row: 47, column: 10 } },
  { start: { row: 48, column: 2 }, end: { row: 48, column: 4 } },
  { start: { row: 48, column: 5 }, end: { row: 48, column: 6 } },
  { start: { row: 48, column: 7 }, end: { row: 48, column: 8 } },
  { start: { row: 49, column: 2 }, end: { row: 49, column: 4 } },
  { start: { row: 49, column: 5 }, end: { row: 49, column: 6 } },
  { start: { row: 49, column: 7 }, end: { row: 49, column: 8 } },
  { start: { row: 50, column: 2 }, end: { row: 50, column: 4 } },
  { start: { row: 50, column: 5 }, end: { row: 50, column: 6 } },
  { start: { row: 51, column: 2 }, end: { row: 51, column: 4 } },
  { start: { row: 52, column: 2 }, end: { row: 52, column: 4 } },
  { start: { row: 53, column: 2 }, end: { row: 53, column: 4 } },
  { start: { row: 56, column: 3 }, end: { row: 56, column: 10 } },
];
exports.naturalVegitationSpecification = {
  col_1: {
    // <- the key should match the actual data key
    displayName: "",
    headerStyle: { font: { color: { rgb: "FFFFFFFF" } } },
  },
  col_2: {
    displayName: "",
    headerStyle: { font: { color: { rgb: "FFFFFFFF" } } },
    cellStyle: (value, row) => {
      if (value === "") {
        return { alignment: { horizontal: "left" } };
      } else if (value === "Spreadsheet Description:") {
        return {
          alignment: {
            wrapText: true,
            vertical: "center",
            horizontal: "center",
          },
          border: {
            top: { style: "medium" },
            right: { style: "medium" },
            bottom: { style: "medium" },
            left: { style: "medium" },
          },
        };
      } else if (value === "Building Parameters") {
        return {
          fill: { fgColor: { rgb: "C6D9F0" } },
          font: { sz: "14", bold: true },
        };
      } else if (value === "Description") {
        return {
          font: { sz: "12", bold: true },
        };
      } else if (value === "Stack Effect Calculation") {
        return {
          fill: { fgColor: { rgb: "C6D9F0" } },
          font: { sz: "14", bold: true },
        };
      } else if (value === "*complete Fugitive Emissions worksheet prior") {
        return { alignment: { horizontal: "left" } };
      } else if (value === "to filling out this spreadsheet") {
        return { alignment: { horizontal: "left" } };
      } else if (
        value ===
        "**data in DARK RED is copied from the Fugitive emissions worksheet"
      ) {
        return { alignment: { horizontal: "left" } };
      } else if (value === "References") {
        return {
          font: { sz: "12", bold: true },
        };
      }
      return {
        border: {
          top: { style: "medium" },
          right: { style: "medium" },
          bottom: { style: "medium" },
          left: { style: "medium" },
        },
        alignment: { wrapText: true },
      };
    },
  },
  col_3: {
    displayName: "",
    headerStyle: { font: { color: { rgb: "FFFFFFFF" } } },
    cellStyle: (value, row) => {
      if (value === "") {
        return {
          alignment: { horizontal: "left" },
        };
      }
      return {
        border: {
          top: { style: "medium" },
          right: { style: "medium" },
          bottom: { style: "medium" },
          left: { style: "medium" },
        },
        alignment: { wrapText: true },
      };
    },
  },
  col_4: {
    displayName: "",
    headerStyle: { font: { color: { rgb: "FFFFFFFF" } } },
    cellStyle: (value, row) => {
      if (value === "") {
        return { alignment: { horizontal: "left" } };
      }
      return {
        border: {
          top: { style: "medium" },
          right: { style: "medium" },
          bottom: { style: "medium" },
          left: { style: "medium" },
        },
        alignment: { wrapText: true, horizontal: "center" },
      };
    },
  },
  col_5: {
    displayName: "",
    headerStyle: { font: { color: { rgb: "FFFFFFFF" } } },
    cellStyle: (value, row) => {
      if (value === "") {
        return {
          alignment: { horizontal: "left" },
        };
      }
      return {
        border: {
          top: { style: "medium" },
          right: { style: "medium" },
          bottom: { style: "medium" },
          left: { style: "medium" },
        },
        alignment: { wrapText: true },
      };
    },
  },
  col_6: {
    displayName: "",
    headerStyle: { font: { color: { rgb: "FFFFFFFF" } } },
    cellStyle: (value, row) => {
      if (value === "") {
        return {
          alignment: { horizontal: "left" },
        };
      }
      return {
        border: {
          top: { style: "medium" },
          right: { style: "medium" },
          bottom: { style: "medium" },
          left: { style: "medium" },
        },
        alignment: { wrapText: true },
      };
    },
  },
  col_7: {
    displayName: "",
    headerStyle: { font: { color: { rgb: "FFFFFFFF" } } },
    cellStyle: (value, row) => {
      if (value === "") {
        return {
          alignment: { horizontal: "left" },
        };
      }
      return {
        border: {
          top: { style: "medium" },
          right: { style: "medium" },
          bottom: { style: "medium" },
          left: { style: "medium" },
        },
        alignment: { wrapText: true },
      };
    },
  },
  col_8: {
    displayName: "",
    headerStyle: { font: { color: { rgb: "FFFFFFFF" } } },
    cellStyle: (value, row) => {
      if (value === "") {
        return {
          alignment: { horizontal: "left" },
        };
      }
      return {
        border: {
          top: { style: "medium" },
          right: { style: "medium" },
          bottom: { style: "medium" },
          left: { style: "medium" },
        },
        alignment: { wrapText: true },
      };
    },
  },
  col_9: {
    displayName: "",
    headerStyle: { font: { color: { rgb: "FFFFFFFF" } } },
    cellStyle: (value, row) => {
      if (value === "") {
        return {
          alignment: { horizontal: "left" },
        };
      }
      return {
        border: {
          top: { style: "medium" },
          right: { style: "medium" },
          bottom: { style: "medium" },
          left: { style: "medium" },
        },
        alignment: { wrapText: true },
      };
    },
  },
  col_10: {
    displayName: "",
    headerStyle: { font: { color: { rgb: "FFFFFFFF" } } },
    cellStyle: (value, row) => {
      if (value === "") {
        return {
          alignment: { horizontal: "left" },
        };
      }
      return {
        border: {
          top: { style: "medium" },
          right: { style: "medium" },
          bottom: { style: "medium" },
          left: { style: "medium" },
        },
        alignment: { wrapText: true },
      };
    },
  },
};
exports.naturalVegitaionData = [
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "Spreadsheet:",
    col_7: "",
    col_8: "Natural Ventilation Calculation",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "Document Number:",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "Client:",
    col_7: "",
    col_8: "ABC Engineering",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "Project Name:",
    col_7: "",
    col_8: "Blackswan c-46-C",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "Project Number:",
    col_7: "",
    col_8: "2016-425",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "Building:",
    col_7: "",
    col_8: "Sour Gas Dehy. Skid (BU-406)",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "*complete Fugitive Emissions worksheet prior",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "Date:",
    col_7: "",
    col_8: "43402",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "to filling out this spreadsheet",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "P&ID:",
    col_7: "",
    col_8: "ABC 16332-PID-00-01-14 to 151",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "**data in DARK RED is copied from the Fugitive emissions worksheet",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "Building Drawing:",
    col_7: "",
    col_8: "Alco Dwg D-2017-8876-50A-001/004",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "Case:",
    col_7: "",
    col_8: "Summer - Louvres 100% Open",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Spreadsheet Description:",
    col_3: "",
    col_4:
      "For naturally ventilated enclosed areas. Air flow due to stack effect (thermal forces) provides adequate ventilation if the inlen and oulet vent openings are properly sized and located (recommended for areas under 1000 cu-ft)",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Rev",
    col_3: "Description",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "Date",
    col_8: "By",
    col_9: "Checked",
    col_10: "Approved",
  },
  {
    col_1: "",
    col_2: "col_1",
    col_3: "Issued for Review",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "2017-09-29",
    col_8: "RWS",
    col_9: "TA",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "0",
    col_3: "Issued for Implementation",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "2019-03-19",
    col_8: "RWS",
    col_9: "TA",
    col_10: "TA",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Building Parameters",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Description",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Outdoor Air Temperature",
    col_3: "",
    col_4: "",
    col_5: "20",
    col_6: "col_3",
    col_7: "68",
    col_8: "col_6",
    col_9: "293.15",
    col_10: "K",
  },
  {
    col_1: "",
    col_2: "Indoor Air Temperature",
    col_3: "",
    col_4: "",
    col_5: "32",
    col_6: "col_3",
    col_7: "89.6",
    col_8: "col_6",
    col_9: "305.15",
    col_10: "K",
  },
  {
    col_1: "",
    col_2: "Length",
    col_3: "",
    col_4: "",
    col_5: "11.6",
    col_6: "m",
    col_7: "38.0596",
    col_8: "ft",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Width",
    col_3: "",
    col_4: "",
    col_5: "4.4",
    col_6: "m",
    col_7: "14.4364",
    col_8: "ft",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Eave Height",
    col_3: "",
    col_4: "",
    col_5: "3.042",
    col_6: "m",
    col_7: "9.980802",
    col_8: "ft",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Eave to Peak Height",
    col_3: "",
    col_4: "",
    col_5: "0.83",
    col_6: "m",
    col_7: "2.72323",
    col_8: "ft",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Volume",
    col_3: "",
    col_4: "",
    col_5: "141.156224",
    col_6: "cu-m",
    col_7: "4984.8897036928",
    col_8: "cu-ft",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2:
      "Vertical Distance Between Upper and Lower Vent Openings                       (center-to-center)",
    col_3: "",
    col_4: "",
    col_5: "2.73",
    col_6: "m",
    col_7: "8.95713",
    col_8: "ft",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Vent Openings",
    col_3: "",
    col_4: "",
    col_5: "Length OR # Circular",
    col_6: "",
    col_7: "Width OR Diameter",
    col_8: "",
    col_9: "Area",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Lower",
    col_3: "Rectangular Vents",
    col_4: "",
    col_5: "0.406",
    col_6: "1.332086",
    col_7: "0.406",
    col_8: "1.332086",
    col_9: "0.164836",
    col_10: "1.774453111396",
  },
  {
    col_1: "",
    col_2: "Upper",
    col_3: "Rectangular Vents",
    col_4: "",
    col_5: "0.3",
    col_6: "0.9843",
    col_7: "0.3",
    col_8: "0.9843",
    col_9: "0.09",
    col_10: "0.96884649",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "Circular Vents",
    col_4: "",
    col_5: "0",
    col_6: "0",
    col_7: "1",
    col_8: "3.281",
    col_9: "0",
    col_10: "0",
  },
  {
    col_1: "",
    col_2: "Number of Vents",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "Lower",
    col_4: "",
    col_5: "4",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "Upper Rectangular",
    col_4: "",
    col_5: "2",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Open Area",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "A1",
    col_4: "",
    col_5: "0.164836",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "A2",
    col_4: "",
    col_5: "0.18",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "% Open",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "Lower Vents",
    col_4: "",
    col_5: "25%",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "Upper Vents",
    col_4: "",
    col_5: "100%",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Effectiveness of Openings",
    col_3: "",
    col_4: "",
    col_5: "100%",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Stack Effect Calculation",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Description",
    col_3: "",
    col_4: "",
    col_5: "Lower/Upper (A1/A2)",
    col_6: "",
    col_7: "Upper/Lower (A2/A1)",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Vent Opening Ratios",
    col_3: "",
    col_4: "",
    col_5: "0.915755555555556",
    col_6: "",
    col_7: "1.09199446722803",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Neutral Pressure Level",
    col_3: "",
    col_4: "",
    col_5: "1.45760422501925",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Natural Ventilation Due to Stack",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "Both openings as smallest",
    col_3: "",
    col_4: "",
    col_5: "2.22825095546979",
    col_6: "Air Changes Per Hour",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "One opening larger than the other",
    col_3: "",
    col_4: "",
    col_5: `${airChange}`,
    col_6: "Air Changes Per Hour",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "References",
    col_3: "",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
  {
    col_1: "",
    col_2: "[1]",
    col_3: "API RP-505",
    col_4: "",
    col_5: "",
    col_6: "",
    col_7: "",
    col_8: "",
    col_9: "",
    col_10: "",
  },
];
